name: Code Quality Check
on:
  pull_request:
    branches:
      - dev
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install flake8
      - name: Run Flake8
        run: flake8 .